CFLAGS  = -Wall -g -pthread
FUENTE1 = prodconspipe1.c
FUENTE2 = prodconspipe2.c
PROG1   = PCPipe1
PROG2   = PCPipe2

all :
	gcc $(CFLAGS) -o $(PROG1) $(FUENTE1)
	gcc $(CFLAGS) -o $(PROG2) $(FUENTE2)

clean :
	-rm $(PROG1) $(PROG2)
